name: 'JS/CSS'

on:
  pull_request: {}
  push: {}

jobs:
  eslint:
    name: 'Run eslint'
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout current revision'
        uses: 'actions/checkout@v3'
      - name: 'Setup Node'
        uses: 'actions/setup-node@v3'
        with:
          node-version: 'lts/*'
          # cache: yarn
      - name: 'Install NPM dependencies'
        run: yarn install
      - name: Lint
        run: yarn lint:scripts

  stylelint:
    name: 'Run stylelint'
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout current revision'
        uses: 'actions/checkout@v3'
      - name: 'Setup Node'
        uses: 'actions/setup-node@v3'
        with:
          node-version: 'lts/*'
          # cache: yarn
      - name: 'Install NPM dependencies'
        run: yarn install
      - name: Lint
        run: yarn lint:styles
